
ZSH=$HOME/.oh-my-zsh
export ZSH=$ZSH

ZSH_THEME="agnoster" # or: gallois
# DISABLE_AUTO_UPDATE="true"
# DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="true"
plugins=(redis-cli history-substring-search)

source $ZSH/oh-my-zsh.sh

# ### ALIASES

alias cassandra="docker run -it --link cassandra:cqlsh --rm cassandra cqlsh cassandra 9042"
alias mongo="docker run -it --link mongo:mongocli --rm mongo mongo mongo:27017"
alias redis="docker run -it --link redis:rediscli --rm redis redis-cli -h redis"
alias npkc="kubectl config use-context prod.balanc3.net && kubectl"
alias cp="cp -i"
alias df="df -h"
alias free="free -m"
alias more="less"
alias npkclog="kubectl config use-context prod.balanc3.net && kubectl get pods | grep %1 | cut -f 1 -d ' ' | xargs -I % zsh -c 'kubectl config use-context prod.balanc3.net && kubectl logs -f --tail 1 %'"

export VISUAL=vim
export EDITOR=$VISUAL
export SHELL=/usr/bin/zsh
export HISTSIZE=4096
export PATH="$PATH:$HOME/.bin:$HOME/bin:node_modules/.bin:/usr/local/share/npm/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin"

#[ -z "$TMUX" ] && exec tmux new -As $WINDOWID
#[ -n "$WINDOWID" ] && [ -z "$TMUX" ] && exec tmux new -As $WINDOWID

