version: '2'
services:
  web:
    image: nextcloud:18
    volumes:
      - nextcloud:/var/www/html
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - default
      - web
    labels:
      - "traefik.frontend.rule=Host:cloud.home.packden.us"
      - "traefik.port=80"
      - "traefik.enable=true"
      - "traefik.backend=cloud"
      - "traefik.docker.network=web"
  db:
    image: mariadb:10.3
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=blathe2342jlk232lj
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=blatheringblatherskite
    volumes:
      - cloud:/var/lib/mysql
    networks:
      - default

networks:
  web:
    external:
      name: web
