version: '2'
services:
  portainer:
    image: portainer/portainer
    volumes:
      - portainer_d:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "9000"
    restart: always
    networks:
      - web
    labels:
      - "traefik.frontend.rule=Host:portainer.home.packden.us"
      - "traefik.port=9000"
      - "traefik.enable=true"
      - "traefik.backend=portainer"
      - "traefik.docker.network=web"

networks:
  web:
    external:
      name: web
